config/routes.rb
Rails.application.routes.draw do

	devise_for :admins, :path => 'admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
	resources :offices
	post 'offices/like'
	post 'offices/sendmail'
	post 'contact/message'
	post 'development/showmessage'
	post 'development/deletemessage'
	post 'dev_sendimage', to: 'contributed_image#send_image'
	post 'dev_show_user_image', to: 'development#show_user_image'
	get 'development/message', to: 'development#message'
	get 'development/contact', to: 'development#contact'
	get 'development/image', to: 'development#image'
	get 'development/count', to: 'development#view_count'
	get 'development', to: 'development#index'
	get 'contact', to: 'contact#index'
	get 'zorba', to: 'zorba#index'
	get 'send_image', to: 'contributed_image#index'
	get 'thank_you', to: 'contributed_image#thank_you'
	get '/404', to: 'errors#not_found'
	get '/500', to: 'errors#internal_server_error'

	root 'offices#index'

end

app/controllers/development_controller.rb
class DevelopmentController < ApplicationController
	before_filter :verify_is_admin
	# index page
	def index
		
	end
	# view count
	def view_count
		@home_page = ViewPage.first.home_page
		@zorba_page = ViewPage.first.zorba_page
		@contact_page = ViewPage.first.contact_page
		@contributed_image_page = ViewPage.first.contributed_image_page
		@allUserImage = UserImage.all.order(created_at: :desc)
		@allUserImage_paging = UserImage.paginate(:page => params[:page], :per_page => 25).order(created_at: :desc)
	end

	# all image page
	def image
		@allImage = Office.all.order(created_at: :desc)
		@allImage_paging = Office.paginate(:page => params[:page], :per_page => 25).order(created_at: :desc)
	end
	# contact page
	def contact
		@allContact = Contact.all.order(created_at: :desc)
		@allContact_paging = Contact.paginate(:page => params[:page], :per_page => 25).order(created_at: :desc)
	end
	# message page
	def message
		# show message
		@allMessage = Message.all.order(created_at: :desc)
		@allMessage_paging = Message.paginate(:page => params[:page], :per_page => 25).order(created_at: :desc)
	end
	def showmessage
		if params[:idMessage].present?
			messageQuy = Message.find(params[:idMessage]);
			render json:{name: messageQuy.name, mail: messageQuy.mail, message: messageQuy.message, send_time: messageQuy.created_at.in_time_zone(7).strftime("%B - %d - %Y  %H : %M"), }
		end
	end
	def deletemessage
		if params[:idMessage].present?
			messageDelete = Message.find {params[:idMessage]}
			messageDelete.destroy
		end
	end

	def show_user_image
		if params[:user_image_id].present?
			userImage = UserImage.find(params[:user_image_id])
			if params[:read].present?
				userImage.dev_readed = true
				userImage.save
			end
			render json:{name: userImage.name, email: userImage.email, title: userImage.title, noted: userImage.noted, image_upload: userImage.image_upload, image_link: userImage.image_link, image_idea: userImage.image_idea, send_time: userImage.created_at.in_time_zone(7).strftime("%B - %d - %Y  %H : %M")}
		end
	end

	private

		def verify_is_admin
			if admin_signed_in?
				# mus have role
			else
				redirect_to root_url
			end
		end
end

app/helpers/development_helper.rb
module DevelopmentHelper
	def facebook_shares(url)
		data = Net::HTTP.get(URI.parse("https://api.facebook.com/method/links.getStats?urls=%%#{URI.escape(url)}&format=json"))
		data = JSON.parse(data)
		data[0]
	end
end

app/views/development/contact.html.erb
<% title "Trang quản trị - Thông tin liên hệ " %>
<div class="development-page">
	<h2>Trang quản trị - Thông tin liên hệ</h2>
	<div class="dev-section all-contact">
		<h3>Có tổng cộng <%= @allContact.length %> thông tin liên hệ</h3>
		<table class="all-contact-table" cellspacing="0" cellpadding="0" >
			<thead>
				<tr>
					<th class="name">Tên</th>
					<th class="email">Email</th>
					<th class="time">Thời gian Subscribe</th>
				</tr>
			</thead>
			<tbody>
				<% @allContact.each do |contact| %>
					<tr>
						<td class="name"><%= contact.name.capitalize %></td>
						<td class="email"><%= contact.email %></td>
						<td class="time"><%= time_ago_in_words(contact.created_at) %> trước</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div class="paging-secction">
			<%= will_paginate @allContact_paging, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>

app/views/development/image.html.erb
<% title "Trang quản trị - Quản lý ảnh " %>
<div class="development-page">
	<h2>Trang quản trị - Quản lý ảnh</h2>
	<div class="dev-section all-image">
		<h3>Có tổng cộng <%= @allImage.length %> ảnh <%= link_to "Tạo mới", new_office_path, :target => "_blank", :class => "new-image-button" %></h3>
		<!-- show all image -->
		<table class="all-image-table" cellspacing="0" cellpadding="0" >
			<tbody>
				<% @allImage.each do |image| %>
					<tr>
						<td class="dev-image-content">
							<div>
								<img src="<%= image.image%>" alt="">
								<div>
									<p class="tit"><%= image.title.capitalize%></p>
									<p class="sub">đăng bởi <%= image.owner.capitalize%></p>
									<p class="sub">vào lúc <%= image.created_at.in_time_zone(7).strftime("%H:%M - %d - %m - %Y") %></p>
									<p class="sub">
										<%= image.like%>
										<i class="fa fa-thumbs-o-up"></i>
										<%= image.view%>
										<i class="fa fa-eye"></i>
										<%= facebook_shares('http://www.congso.club/offices/' + image.slug)["comment_count"] %>
										<i class="fa fa-comments-o"></i>
										<%= facebook_shares('http://www.congso.club/offices/' + image.slug)["share_count"] %>
										<i class="fa fa-share-square-o"></i>
									</p>
								</div>
								<span class="clear-fix"></span>
							</div>
						</td>
						<td class="dev-image-button">
							<%= link_to "Xem", image, :target => "_blank" %>
						</td>
						<td class="dev-image-button">
							<%= link_to 'Sửa', edit_office_path(image), :target => "_blank" %>
						</td>
						<td class="dev-image-button">
							<%= link_to 'Xóa', image, method: :delete, data: { confirm: 'Chắc chắn muốn xóa ảnh này ?' } %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div class="paging-secction">
			<%= will_paginate @allImage_paging, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>

app/views/development/index.html.erb
<% title "Trang quản trị " %>
<div class="development-page">
	<h2>Trang quản trị - Development</h2>
	<div class="dev-section main-content">
		<div>
			<%= link_to(development_message_path) do%>
				<div class="main-element message">
					<p>Tin nhắn</p>
				</div>
			<% end %>
			<%= link_to(development_contact_path) do%>
				<div class="main-element contact">
					<p>Theo dõi</p>
				</div>
			<% end %>
			<%= link_to(development_image_path) do%>
				<div class="main-element image">
					<p>Quản lý ảnh</p>
				</div>
			<% end %>
			<%= link_to(development_count_path) do%>
				<div class="main-element view_count">
					<p>Thống kê</p>
				</div>
			<% end %>
			<div class="clear-fix"></div>
		</div>
	</div>
</div>

app/views/development/message.html.erb
<% title "Trang quản trị - Tin nhắn" %>
<div class="development-page">
	<h2>Trang quản trị - Tin nhắn</h2>
	<div class="all-message dev-section">
	<h3>Có tổng cộng <%= @allMessage.length %> tin nhắn</h3>
		<!-- show all image -->
		<table class="all-messages-table" cellspacing="0" cellpadding="0" >
			<thead>
				<tr>
					<th class="name">Tên</th>
					<th class="time">Thời gian</th>
					<th class="show">Xem</th>
					<th class="delete">Xóa</th>
				</tr>
			</thead>
			<tbody>
				<% @allMessage.each do |message| %>
					<tr name="messagerowid<%= message.id %>">
						<td class="tb-data-left"><%= message.name.capitalize %></td>
						<td class=""><%= time_ago_in_words(message.created_at) %> trước</td>
						<td class="show-button" onclick="showMessage(<%= message.id %>)">Đọc tin nhắn</td>
						<td class="delete-button" onclick="return deleteMessage(<%= message.id %>)">Xóa tin nhắn</td>
	 				</tr>
 				<% end %>
			</tbody>
		</table>
		<div class="paging-secction">
			<%= will_paginate @allMessage_paging, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
	<div class="show-modal-box">
		<div class="modal-content-box">
			<div class="modal-header">
				<!-- modal title -->
				<h3 class="modal-title">Tin nhắn</h3>
				<!-- modal close button -->
				<div class="close-button" onclick="closeMessage()"></div>
			</div>
			<!-- modal content box -->
			<div class="modal-content">
				<div class="message">
					<p class="name"></p>
					<p class="email"></p>
					<p class="send-time"></p>
					<p class="message"></p>
				</div>
			</div>
		</div>
	</div>
	<div class="comfirm-box">
		<div >
			<h3>Bạn có chắc chắn muốn xóa ?</h3>
			<button class="false-button" onclick="confirmDelete(false)">Không</button>
			<button class="true-button" name="" onclick="confirmDelete(true)">Có</button>
		</div>
	</div>
</div>

app/views/development/view_count.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% title "Trang quản trị - Thống kê truy cập" %>
<div class="development-page">
	<h2>Trang quản trị - Thống kê truy cập</h2>
	<div class="dev-section all-image">
		<%= pie_chart [ ["Trang chủ", "#{@home_page}"], ["Về chúng tôi", "#{@zorba_page}"], ["Liên hệ", "#{@contact_page}"], ["Đóng góp ảnh", "#{@contributed_image_page}"] ] %>
		<%= column_chart [ ["Trang chủ", "#{@home_page}"], ["Về chúng tôi", "#{@zorba_page}"], ["Liên hệ", "#{@contact_page}"], ["Đóng góp ảnh", "#{@contributed_image_page}"]], stacked: true %>
	</div>
	<h2>Trang quản trị - Ảnh người dùng gửi</h2>
	<div class="dev-section user-image">
		<h3>Có tổng cộng <%= @allUserImage.length %> ảnh được gửi</h3>
		<table class="all-user-image-table" cellspacing="0" cellpadding="0" >
			<thead>
				<tr>
					<th class="email">Email</th>
					<th class="title">Tiêu đề</th>
					<th class="time">Thời gian gửi</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @allUserImage.each do |user_image| %>
					<tr class="<% if user_image.dev_readed%>readed<% else %>show<% end %>" id="<%= user_image.id %>">
						<td class="email"><%= user_image.email %></td>
						<td class="title"><%= user_image.title %></td>
						<td class="time"><%= time_ago_in_words(user_image.created_at) %> trước</td>
						<td class="show-button" onclick="showUserSendImage(<%= user_image.id %>)">Xem</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div class="paging-secction">
			<%= will_paginate @allUserImage_paging, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>
<script type="text/javascript">
	function showUserSendImage (user_image_id){
		trTagView = $('.development-page .user-image .all-user-image-table tr#' + user_image_id);
		if (trTagView.attr('class') == 'show') {
			var readedThis = true;
			trTagView.removeClass('show');
			trTagView.addClass('readed');
		};
		if (readedThis) {
			var userImageData = {"user_image_id": user_image_id, "read" : true};
		}else{
			var userImageData = {"user_image_id": user_image_id};
		};
		// call ajax
		$.ajax({
			url: "/dev_show_user_image",
			type: "POST",
			data: userImageData,
			success: function(data) {
				setData( data["name"], data["email"], data["title"], data["noted"], data["image_upload"], data["image_link"], data["image_idea"], data["send_time"] );
				$('.user-image-modal-box').slideDown(400);
			}
		});
	};
	function setData (name, email, title, noted, image_upload, image_link, image_idea, send_time) {
		if (name != "") {
			$('.user-image-modal-box .user-image-modal-content h3.message-by').html(name);
			$('.user-image-modal-box .user-image-modal-content .name').html(name);
		} else{
			$('.user-image-modal-box .user-image-modal-content h3.message-by').html(email);
			$('.user-image-modal-box .user-image-modal-content .name').html("ẩn danh");
		};
		$('.user-image-modal-box .user-image-modal-content .email').html(email);
		$('.user-image-modal-box .user-image-modal-content .time').html(send_time);
		$('.user-image-modal-box .user-image-modal-content .title').html(title);
		$('.user-image-modal-box .user-image-modal-content .noted').html(noted);
		if (image_upload != null) {
			$('.user-image-modal-box .user-image-modal-content .image-title').text('Ảnh Upload');
			imgFather = $('.user-image-modal-box .user-image-modal-content .image');
			imgFather.append('<img src="' + image_upload + '" alt="">');
		}else{
			if (image_link != null) {
				$('.user-image-modal-box .user-image-modal-content .image-title').text('Đường dẫn ảnh');
				$('.user-image-modal-box .user-image-modal-content .image').html(image_link);
			}else{
				if (image_idea != null) {
					$('.user-image-modal-box .user-image-modal-content .image-title').text('Ý tưởng');
					$('.user-image-modal-box .user-image-modal-content .image').html(image_idea);
				}
			};
		};
	};
	function hideAndClearData(){
		$('.user-image-modal-box').slideUp(400);
		$('.user-image-modal-box .user-image-modal-content .image').html("");
	}
</script>
<div class="user-image-modal-box">
	<div class="user-image-modal-content" >
		<h3 class="message-by"></h3>
		<div class="close-button" onclick="hideAndClearData()"></div>
		<div class="content">
			<p class="name"></p>
			<p class="email"></p>
			<p class="time"></p>
			<p class="title"></p>
			<p class="image-title"></p>
			<p class="image"></p>
			<p class="noted"></p>
		</div>
	</div>
</div>