config/routes.rb
Rails.application.routes.draw do

	devise_for :admins, :path => 'admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
	resources :offices
	post 'offices/like'
	post 'offices/sendmail'
	post 'contact/message'
	post 'development/showmessage'
	post 'development/deletemessage'
	post 'dev_sendimage', to: 'contributed_image#send_image'
	post 'dev_show_user_image', to: 'development#show_user_image'
	get 'development/message', to: 'development#message'
	get 'development/contact', to: 'development#contact'
	get 'development/image', to: 'development#image'
	get 'development/count', to: 'development#view_count'
	get 'development', to: 'development#index'
	get 'contact', to: 'contact#index'
	get 'zorba', to: 'zorba#index'
	get 'send_image', to: 'contributed_image#index'
	get 'thank_you', to: 'contributed_image#thank_you'
	get '/404', to: 'errors#not_found'
	get '/500', to: 'errors#internal_server_error'

	root 'offices#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
		<meta charset="UTF-8">
		<meta name="description" content="Congso.club là trang web mang lại tiếng cười cho mọi người, bằng những hình ảnh vui nhộn và tiêu đề thú vị. Trang web dành riêng cho dân công sở và văn phòng.">
		<meta name="keywords" content="congso.club, anh vui cong so, chuyen cuoi cong so, van phong vui, cong so vui">
		<title><%="Congso.club | " + yield(:title)%></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag 'favico.png' %>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	</head>
	<body>
		<!-- google analytics -->
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-73627739-1', 'auto');
			ga('send', 'pageview');

		</script>
		<!-- notice box -->
		<div class="notice-box">
			<div class="notice-content">
				<div class="notice-text">
					<p class="text">Notice box</p>    
				</div>
			</div>
		</div>
		<!-- end notice box -->
		<!-- header -->
		<header>
			<div class="header-box">
				<%= link_to(root_url) do%>
					<h1 class="logo-text">Congso.club</h1>
				<% end %>
				<div class="clear-fix"></div>
				<div class="header-navigation-bar">
					<ul>
						<li><%= link_to "Về chúng tôi", zorba_path %></li>
						<% if !admin_signed_in? %>
							<li><%= link_to "Gửi ảnh", send_image_path %></li>
							<li><%= link_to "Liên hệ", contact_path %></li>
						<% end %>
						<% if admin_signed_in? %>
							<li><%= link_to "Trang quản trị", development_path %></li>
						<% end %>
						<% if admin_signed_in? %>
							<li>
								<%= link_to "Đăng xuất", destroy_admin_session_path, :method => :delete %>
							</li>
						<% end %>
						<div class="clear-fix"></div>
					</ul>
				</div>
			</div>
		</header>
		<!-- end header -->
		<!-- main content -->
		<div class="main-content">
			<%= yield %>
		</div>
		<!-- end main content -->
		<!-- follow box -->
		<div class="page-secction follow-us-by-mail">
			<h2 class="page-title">Đăng kí để cười nhiều hơn mỗi ngày</h2>
			<div class="follow">
				<input class= "name" type="text" name="name" value="" placeholder="Tên của bạn">
				<input class= "email" type="text" name="email" value="" placeholder="Email">
				<button id="send-email" onclick="addNewFollow();">Theo dõi</button>
				<div class="clear-fix"></div>
			</div>
		</div>
		<!-- footer -->
		<footer class="page-secction footer-page">
			<ul>
				<a target="blank" href="https://www.facebook.com/ngocquyhoang.93"><li class="icon facebook"></li></a>
				<a target="blank" href="https://twitter.com/malloryandbob"><li class="icon twitter"></li></a>
				<a target="blank" href="https://plus.google.com/u/0/101396476640771423396"><li class="icon googleplus"></li></a>
				<a target="blank" href="https://www.youtube.com/channel/UCio7sbHpBKOJShbBkDmcs2w"><li class="icon youtube"></li></a>
				<div class="clear-fix"></div>
			</ul>
			<div class="design-by">
				<div>
					<h2 id="design-text" class="page-title">Design by </h2>
					<%= link_to (zorba_path) do %>
						<%= image_tag("per-logo.png", class: "zorba-logo") %>
					<% end %>
					<div class="clear-fix"></div>
				</div>
			</div>
			<div class="hiworld">
				Power of <a href="http://hiworld.com.vn/" target="_blank">Hiworld.JSC</a>
			</div>
		</footer>
		<!-- end footer -->
	</body>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!--facebook sdk-->
	<div id="fb-root"></div>
	<script>
		window.fbAsyncInit = function() {
			FB.init({
				appId      : '717508901713184',
				xfbml      : true,
				version    : 'v2.5'
			});
		};
		(function(d, s, id){
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) {return;}
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/vi_VN/sdk.js";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
	<!--end call facebook sdk-->
</html>